name       : print-manager
version    : 17.04.3
release    : 2
source     :
    - https://download.kde.org/stable/applications/17.04.3/src/print-manager-17.04.3.tar.xz : 566dc20b88324211b2cb133cd459893aa178c156d1554594d57cd12ce0e4a170
license    : GPL-2.0
component  : desktop.kde.core
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
