name       : print-manager
version    : 19.08.3
release    : 30
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/print-manager-19.08.3.tar.xz : c6420dfa711fc68a6d681d27521eac3c9f1060e57f048594b43f2941a78320ee
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
