name       : print-manager
version    : 19.12.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/print-manager-19.12.0.tar.xz : 166b9eef8eb94b0a9cbf257807c4432bef0489d7e2c401865a3fd028426797a5
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
