name       : print-manager
version    : 21.08.0
release    : 53
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.0/src/print-manager-21.08.0.tar.xz : 2e638530e7c844adfaceec916377ff79ab8f65f5a36a690c814901729dccec06
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
