name       : print-manager
version    : 20.12.3
release    : 48
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/print-manager-20.12.3.tar.xz : 8a375086ca58487f79ae16c24792e1a9b0b609449aeb105ea9df945b12cd7ca6
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
