name       : print-manager
version    : 20.12.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.0/src/print-manager-20.12.0.tar.xz : da373dbc907eda513ee8d41b8b2b3a118d390bae62b829c77076f63b1c3168d3
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
