name       : print-manager
version    : 19.12.3
release    : 34
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.3/src/print-manager-19.12.3.tar.xz : 74c13802a65136539b4542fec10fb248149a3324e8060e947a8f305ce665269a
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
