name       : print-manager
version    : 21.04.0
release    : 49
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.0/src/print-manager-21.04.0.tar.xz : 4020fb437e11ac6b4094378f17fadbdc3605976967eadf244ac64b6204c4b7cc
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
