name       : print-manager
version    : 17.08.1
release    : 3
source     :
    - https://download.kde.org/stable/applications/17.08.1/src/print-manager-17.08.1.tar.xz : 369648d1b4a91b2b5ac1e97c74c8323d8938a41b975fefc89e7bf04f17266538
license    : GPL-2.0
component  : desktop.kde.core
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
