name       : print-manager
version    : 22.04.2
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/print-manager-22.04.2.tar.xz : bfba2fc35807095c65e42d27fddf03f22c8dd3af8724ad6ac08ba3cf2979b652
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
