name       : print-manager
version    : 19.04.2
release    : 25
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.2/src/print-manager-19.04.2.tar.xz : c889c6f96c854bb0ec1e37d99d907dbe425b72f6b4221d6e65fa9b83a173c81c
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
