name       : print-manager
version    : 23.04.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/print-manager-23.04.0.tar.xz : abe326ecf653a80ab88438ce28fe094d8fd3da964f2b6660b5bb609b868ac5bd
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
