name       : print-manager
version    : 21.12.1
release    : 58
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.1/src/print-manager-21.12.1.tar.xz : 830f195597260d4f3956ca0c4543bad44fba91143fc327b0ca0a7eaa1addb17b
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
