name       : print-manager
version    : 22.08.3
release    : 64
source     :
    - https://cdn.download.kde.org/stable/release-service/22.08.3/src/print-manager-22.08.3.tar.xz : 37d46e7ae9dc545b322a900b3a25433cd4d1b335d177fc85733df1e4f1647bfb
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
