name       : print-manager
version    : 19.08.1
release    : 28
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.1/src/print-manager-19.08.1.tar.xz : b1fd9aa067329a4f5bb715e7db736160954bbec303be0ba5bc8f98852071e731
license    : GPL-2.0-or-later
component  : desktop.kde.core
optimize   : lto
libsplit   : no
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
builddeps  :
    - pkgconfig(Qt5Qml)
    - cups-devel
    - extra-cmake-modules
    - kcmutils-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
