name       : print-manager
version    : 20.12.2
release    : 47
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/print-manager-20.12.2.tar.xz : 2d82bcd565f6fd38b63f0e30d469a7d89eb489b423f8b5decd95366c9f7629e4
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
