name       : print-manager
version    : 21.12.3
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/print-manager-21.12.3.tar.xz : 0b6dd52a7f1b1aabd95202b4cce227dba719fb51187506072a75479876d93be1
homepage   : https://kde.org/
license    : GPL-2.0-or-later
component  : desktop.kde.core
summary    : Tool for managing print jobs and printers
description: |
    Tool for managing print jobs and printers on the KDE Plasma desktop.
optimize   : lto
libsplit   : no
builddeps  :
    - pkgconfig(Qt5Quick)
    - cups-devel
    - kcmutils-devel
    - kdbusaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - plasma-framework-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
